// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicGallery } from "./plasmic/sailor_alpha/PlasmicGallery";

function Gallery_(props, ref) {
  // Use PlasmicGallery to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicGallery are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all GalleryProps here, but feel free
  // to do whatever works for you.
  // return <PlasmicGallery root={{ ref }} {...props} />;
  return <PlasmicGallery
  root={{ ref,
    props: { ...props,
    onLoad: () => loadingGallery()
    }
  }}
  />;

}

const Gallery = React.forwardRef(Gallery_);

export default Gallery;

var rendering = true;
function loadingGallery() {
  if (!rendering) return;
  rendering = false;
  console.log("Switching image . . . ");

  // var form = document.getElementsByTagName('form');
  // form[0].addEventListener("submit", (e) => { funcDownload(e) });

  document.getElementById('FocusImg').decoding = "sync";

  var changePic = document.getElementsByTagName('picture');

  //console.log(changePic);

  for( let i = 0 ; i < changePic.length ; i++) {
    changePic[i].addEventListener("click", (e) => {
      clickGallery(e);
      //console.log("success!: ", e.target.attributes.src.textContent);

      //var new_image = new Image();
      //set up the new image
      //new_image.id = "theText";
      //new_image.src = image.src;           
      // insert new image and remove old
      //image.parentNode.insertBefore(new_image,image);
      //image.parentNode.removeChild(image);

      //console.log("success!: ", e.target.attributes.src.textContent);
      //document.getElementById('FocusImg').src = e.target.attributes.src.textContent;
      //console.log("success 2!: ", document.getElementById('FocusImg'));
    });
  }

  //changePic.addEventListener("click", (e) => { console.log("success!") });

}

function clickGallery(e) {
  console.log("e.target.attributes.src.textContent: ", e.target.attributes.src.textContent);

  var image = document.getElementById('FocusImg');
  var new_image = new Image();
  //set up the new image
  new_image.id = "FocusImg2";
  new_image.src = e.target.attributes.src.textContent;           
  // insert new image and remove old
  image.parentNode.insertBefore(new_image,image);
  //image.parentNode.removeChild(image);

  //console.log("success!: ", e.target.attributes.src.textContent);
  //document.getElementById('FocusImg').src = e.target.attributes.src.textContent;
  //console.log("success 2!: ", document.getElementById('FocusImg'));
}