// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6tP4H2YXq73abyMEePhpsf
// Component: sfUx3YtoOJF
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_sailor_alpha.module.css"; // plasmic-import: 6tP4H2YXq73abyMEePhpsf/projectcss
import sty from "./PlasmicMyHeader.module.css"; // plasmic-import: sfUx3YtoOJF/css
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: 7TF_5MOPI-/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: DWFVge57vL/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: qRmAp_Q_rQ/icon
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: lZXQJCYXE-/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: jVyaTlq74k/icon
import Vector5Icon from "./icons/PlasmicIcon__Vector5"; // plasmic-import: g1FkF8DalH/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: 0vaB1G-gxVg/icon
import Vector6Icon from "./icons/PlasmicIcon__Vector6"; // plasmic-import: CQN_RaB1qX4/icon
import Group4Icon from "./icons/PlasmicIcon__Group4"; // plasmic-import: X7MFUIHrVnf/icon
import Vector7Icon from "./icons/PlasmicIcon__Vector7"; // plasmic-import: VdL2x5EHJqM/icon
import Vector8Icon from "./icons/PlasmicIcon__Vector8"; // plasmic-import: Sl6WxeB-XjK/icon
import Vector9Icon from "./icons/PlasmicIcon__Vector9"; // plasmic-import: VUUxUU0Snc9/icon
import Vector10Icon from "./icons/PlasmicIcon__Vector10"; // plasmic-import: Tf279w1rZIt/icon
import Group5Icon from "./icons/PlasmicIcon__Group5"; // plasmic-import: iV45GyIvt71/icon
import Group6Icon from "./icons/PlasmicIcon__Group6"; // plasmic-import: isENxjcGSDv/icon
import Vector11Icon from "./icons/PlasmicIcon__Vector11"; // plasmic-import: UVAe3cG5bL-/icon
import Vector12Icon from "./icons/PlasmicIcon__Vector12"; // plasmic-import: irjNS_NSkIK/icon
import frameRaK5Oy1GJsO from "./images/frame.svg"; // plasmic-import: RaK5OY1GJsO/picture
import frame2C8PdPm9PxOc from "./images/frame2.svg"; // plasmic-import: c8PdPm9pxOC/picture
import frame3UauVmUohuUf from "./images/frame3.svg"; // plasmic-import: uauVMUohuUf/picture

export const PlasmicMyHeader__VariantProps = new Array();

export const PlasmicMyHeader__ArgProps = new Array();

function PlasmicMyHeader__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"group1"}
        data-plasmic-override={overrides.group1}
        className={classNames(projectcss.all, sty.group1)}
      >
        <div
          data-plasmic-name={"frame"}
          data-plasmic-override={overrides.frame}
          className={classNames(projectcss.all, sty.frame)}
        >
          <div
            data-plasmic-name={"group"}
            data-plasmic-override={overrides.group}
            className={classNames(projectcss.all, sty.group)}
          >
            <div
              data-plasmic-name={"objects"}
              data-plasmic-override={overrides.objects}
              className={classNames(projectcss.all, sty.objects)}
            >
              <GroupIcon
                className={classNames(projectcss.all, sty.svg__mT5Zx)}
                role={"img"}
              />

              <VectorIcon
                className={classNames(projectcss.all, sty.svg___3Vlbh)}
                role={"img"}
              />

              <Vector3Icon
                className={classNames(projectcss.all, sty.svg__m2Guj)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>

      <div
        data-plasmic-name={"group2"}
        data-plasmic-override={overrides.group2}
        className={classNames(projectcss.all, sty.group2)}
      >
        <div
          data-plasmic-name={"frame2"}
          data-plasmic-override={overrides.frame2}
          className={classNames(projectcss.all, sty.frame2)}
        >
          <div
            data-plasmic-name={"group3"}
            data-plasmic-override={overrides.group3}
            className={classNames(projectcss.all, sty.group3)}
          >
            <div
              data-plasmic-name={"objects2"}
              data-plasmic-override={overrides.objects2}
              className={classNames(projectcss.all, sty.objects2)}
            >
              <Group2Icon
                className={classNames(projectcss.all, sty.svg__mhx0M)}
                role={"img"}
              />

              <Vector4Icon
                className={classNames(projectcss.all, sty.svg__gs9Bi)}
                role={"img"}
              />

              <Vector5Icon
                className={classNames(projectcss.all, sty.svg__nm19)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>

      <div
        data-plasmic-name={"group4"}
        data-plasmic-override={overrides.group4}
        className={classNames(projectcss.all, sty.group4)}
      >
        <div
          data-plasmic-name={"frame3"}
          data-plasmic-override={overrides.frame3}
          className={classNames(projectcss.all, sty.frame3)}
        >
          <div
            data-plasmic-name={"group5"}
            data-plasmic-override={overrides.group5}
            className={classNames(projectcss.all, sty.group5)}
          >
            <div
              data-plasmic-name={"objects3"}
              data-plasmic-override={overrides.objects3}
              className={classNames(projectcss.all, sty.objects3)}
            >
              <Group3Icon
                className={classNames(projectcss.all, sty.svg__zC4V0)}
                role={"img"}
              />

              <Vector6Icon
                className={classNames(projectcss.all, sty.svg___2OlUc)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>

      <div
        data-plasmic-name={"group6"}
        data-plasmic-override={overrides.group6}
        className={classNames(projectcss.all, sty.group6)}
      >
        <div
          data-plasmic-name={"frame4"}
          data-plasmic-override={overrides.frame4}
          className={classNames(projectcss.all, sty.frame4)}
        >
          <div
            data-plasmic-name={"group7"}
            data-plasmic-override={overrides.group7}
            className={classNames(projectcss.all, sty.group7)}
          >
            <div
              data-plasmic-name={"objects4"}
              data-plasmic-override={overrides.objects4}
              className={classNames(projectcss.all, sty.objects4)}
            >
              <Group4Icon
                className={classNames(projectcss.all, sty.svg__vDaUv)}
                role={"img"}
              />

              <Vector7Icon
                className={classNames(projectcss.all, sty.svg__kog9Z)}
                role={"img"}
              />

              <Vector8Icon
                className={classNames(projectcss.all, sty.svg__iEzyp)}
                role={"img"}
              />

              <Vector9Icon
                className={classNames(projectcss.all, sty.svg__m7WIy)}
                role={"img"}
              />

              <Vector10Icon
                className={classNames(projectcss.all, sty.svg__eoTFg)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>

      <div
        data-plasmic-name={"group8"}
        data-plasmic-override={overrides.group8}
        className={classNames(projectcss.all, sty.group8)}
      >
        <div
          data-plasmic-name={"frame5"}
          data-plasmic-override={overrides.frame5}
          className={classNames(projectcss.all, sty.frame5)}
        >
          <div
            data-plasmic-name={"group9"}
            data-plasmic-override={overrides.group9}
            className={classNames(projectcss.all, sty.group9)}
          >
            <div
              data-plasmic-name={"objects5"}
              data-plasmic-override={overrides.objects5}
              className={classNames(projectcss.all, sty.objects5)}
            >
              <Group5Icon
                className={classNames(projectcss.all, sty.svg__eiDnJ)}
                role={"img"}
              />

              <div
                data-plasmic-name={"circle"}
                data-plasmic-override={overrides.circle}
                className={classNames(projectcss.all, sty.circle)}
              >
                <Group6Icon
                  className={classNames(projectcss.all, sty.svg__cQlus)}
                  role={"img"}
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div
        data-plasmic-name={"group10"}
        data-plasmic-override={overrides.group10}
        className={classNames(projectcss.all, sty.group10)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__zJmSi)}
          displayHeight={"29px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"89.75px"}
          loading={"lazy"}
          src={{
            src: frameRaK5Oy1GJsO,
            fullWidth: 89.75,
            fullHeight: 29,
            aspectRatio: 3.103448
          }}
        />

        <a
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.link___9LA4W
          )}
          href={"/mint"}
        >
          {"MINT"}
        </a>
      </div>

      <div
        data-plasmic-name={"group11"}
        data-plasmic-override={overrides.group11}
        className={classNames(projectcss.all, sty.group11)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__gbE5U)}
          displayHeight={"26px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"84.764px"}
          loading={"lazy"}
          src={{
            src: frame2C8PdPm9PxOc,
            fullWidth: 84.764,
            fullHeight: 26,
            aspectRatio: 3.269231
          }}
        />

        <a
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.link__tl8V
          )}
          href={"/roadmap"}
        >
          {"ROADMAP"}
        </a>
      </div>

      <div
        data-plasmic-name={"group12"}
        data-plasmic-override={overrides.group12}
        className={classNames(projectcss.all, sty.group12)}
      >
        <Vector11Icon
          className={classNames(projectcss.all, sty.svg__nvQnj)}
          role={"img"}
        />

        <a
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.link__cJpew
          )}
          href={"/artist"}
        >
          {"THE ARTIST"}
        </a>
      </div>

      <div
        data-plasmic-name={"group13"}
        data-plasmic-override={overrides.group13}
        className={classNames(projectcss.all, sty.group13)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__fsyrM)}
          displayHeight={"35.768px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"85.763px"}
          loading={"lazy"}
          src={{
            src: frame3UauVmUohuUf,
            fullWidth: 85.763,
            fullHeight: 35.768,
            aspectRatio: 2.388889
          }}
        />

        <a
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.link__wgqh
          )}
          href={"/gallery"}
        >
          {"GALLERY"}
        </a>
      </div>

      <div
        data-plasmic-name={"group14"}
        data-plasmic-override={overrides.group14}
        className={classNames(projectcss.all, sty.group14)}
      >
        <Vector12Icon
          className={classNames(projectcss.all, sty.svg__m9Ryl)}
          role={"img"}
        />

        <a
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.link__pShL
          )}
          href={"/artwork"}
        >
          {"ARTWORK"}
        </a>
      </div>

      <div
        data-plasmic-name={"group15"}
        data-plasmic-override={overrides.group15}
        className={classNames(projectcss.all, sty.group15)}
      >
        {false ? (
          <div
            data-plasmic-name={"rectangle1"}
            data-plasmic-override={overrides.rectangle1}
            className={classNames(projectcss.all, sty.rectangle1)}
          />
        ) : null}
        {false ? (
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {"LOGO"}
          </div>
        ) : null}

        <a
          data-plasmic-name={"signat101"}
          data-plasmic-override={overrides.signat101}
          className={classNames(projectcss.all, projectcss.a, sty.signat101)}
          href={"/"}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "group1",
    "frame",
    "group",
    "objects",
    "group2",
    "frame2",
    "group3",
    "objects2",
    "group4",
    "frame3",
    "group5",
    "objects3",
    "group6",
    "frame4",
    "group7",
    "objects4",
    "group8",
    "frame5",
    "group9",
    "objects5",
    "circle",
    "group10",
    "group11",
    "group12",
    "group13",
    "group14",
    "group15",
    "rectangle1",
    "text",
    "signat101"
  ],

  group1: ["group1", "frame", "group", "objects"],
  frame: ["frame", "group", "objects"],
  group: ["group", "objects"],
  objects: ["objects"],
  group2: ["group2", "frame2", "group3", "objects2"],
  frame2: ["frame2", "group3", "objects2"],
  group3: ["group3", "objects2"],
  objects2: ["objects2"],
  group4: ["group4", "frame3", "group5", "objects3"],
  frame3: ["frame3", "group5", "objects3"],
  group5: ["group5", "objects3"],
  objects3: ["objects3"],
  group6: ["group6", "frame4", "group7", "objects4"],
  frame4: ["frame4", "group7", "objects4"],
  group7: ["group7", "objects4"],
  objects4: ["objects4"],
  group8: ["group8", "frame5", "group9", "objects5", "circle"],
  frame5: ["frame5", "group9", "objects5", "circle"],
  group9: ["group9", "objects5", "circle"],
  objects5: ["objects5", "circle"],
  circle: ["circle"],
  group10: ["group10"],
  group11: ["group11"],
  group12: ["group12"],
  group13: ["group13"],
  group14: ["group14"],
  group15: ["group15", "rectangle1", "text", "signat101"],
  rectangle1: ["rectangle1"],
  text: ["text"],
  signat101: ["signat101"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMyHeader__ArgProps,
      internalVariantPropNames: PlasmicMyHeader__VariantProps
    });

    return PlasmicMyHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMyHeader";
  } else {
    func.displayName = `PlasmicMyHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicMyHeader = Object.assign(
  // Top-level PlasmicMyHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    group1: makeNodeComponent("group1"),
    frame: makeNodeComponent("frame"),
    group: makeNodeComponent("group"),
    objects: makeNodeComponent("objects"),
    group2: makeNodeComponent("group2"),
    frame2: makeNodeComponent("frame2"),
    group3: makeNodeComponent("group3"),
    objects2: makeNodeComponent("objects2"),
    group4: makeNodeComponent("group4"),
    frame3: makeNodeComponent("frame3"),
    group5: makeNodeComponent("group5"),
    objects3: makeNodeComponent("objects3"),
    group6: makeNodeComponent("group6"),
    frame4: makeNodeComponent("frame4"),
    group7: makeNodeComponent("group7"),
    objects4: makeNodeComponent("objects4"),
    group8: makeNodeComponent("group8"),
    frame5: makeNodeComponent("frame5"),
    group9: makeNodeComponent("group9"),
    objects5: makeNodeComponent("objects5"),
    circle: makeNodeComponent("circle"),
    group10: makeNodeComponent("group10"),
    group11: makeNodeComponent("group11"),
    group12: makeNodeComponent("group12"),
    group13: makeNodeComponent("group13"),
    group14: makeNodeComponent("group14"),
    group15: makeNodeComponent("group15"),
    rectangle1: makeNodeComponent("rectangle1"),
    text: makeNodeComponent("text"),
    signat101: makeNodeComponent("signat101"),
    // Metadata about props expected for PlasmicMyHeader
    internalVariantProps: PlasmicMyHeader__VariantProps,
    internalArgProps: PlasmicMyHeader__ArgProps
  }
);

export default PlasmicMyHeader;
/* prettier-ignore-end */
