// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6tP4H2YXq73abyMEePhpsf
// Component: opTqQ96dfN
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 9HJOL_ndHV/component
import { useScreenVariants as useScreenVariantsu0VQjvxy5SkDm } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: U0vQjvxy5SKDm/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_sailor_alpha.module.css"; // plasmic-import: 6tP4H2YXq73abyMEePhpsf/projectcss
import sty from "./PlasmicVision.module.css"; // plasmic-import: opTqQ96dfN/css
import Vector39Icon from "./icons/PlasmicIcon__Vector39"; // plasmic-import: 6_cJG0lEE2/icon
import Frame18Icon from "./icons/PlasmicIcon__Frame18"; // plasmic-import: TlvA4yYfff/icon
import Vector37Icon from "./icons/PlasmicIcon__Vector37"; // plasmic-import: -oEINKCMy/icon
import vector389MQpMs7J2O from "./images/vector38.svg"; // plasmic-import: 9MQpMS7J2o/picture
import frame19NFnEizwfIa from "./images/frame19.svg"; // plasmic-import: NFnEIZWFIa/picture

export const PlasmicVision__VariantProps = new Array();

export const PlasmicVision__ArgProps = new Array();

export const defaultVision__Args = {};

function PlasmicVision__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultVision__Args, props.args);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsu0VQjvxy5SkDm()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              data-plasmic-name={"figmaPaste"}
              data-plasmic-override={overrides.figmaPaste}
              className={classNames(projectcss.all, sty.figmaPaste)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__pzJUs)}
                displayHeight={"396px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"433px"}
                loading={"lazy"}
                src={{
                  src: vector389MQpMs7J2O,
                  fullWidth: 433,
                  fullHeight: 396,
                  aspectRatio: 1.093434
                }}
              />

              <Vector39Icon
                className={classNames(projectcss.all, sty.svg__kyeRy)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cQlfC
                )}
              >
                {"Imagine the tomorrow's Sailor"}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__k2YgU)}
                displayHeight={"396px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"433px"}
                loading={"lazy"}
                src={{
                  src: vector389MQpMs7J2O,
                  fullWidth: 433,
                  fullHeight: 396,
                  aspectRatio: 1.093434
                }}
              />

              <Vector39Icon
                className={classNames(projectcss.all, sty.svg___9ZaI2)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2Srvs
                )}
              >
                {
                  'Sailor invites whoever is ready to learn about the world, to dive into his creative universe and to share his vision. He will offer \nto discover him under all these aspects \nwith the operation "Hut", which will be a unique journey, mixing the real and the virtual.'
                }
              </div>

              <div
                data-plasmic-name={"immersionInTheSailorsWorld"}
                data-plasmic-override={overrides.immersionInTheSailorsWorld}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.immersionInTheSailorsWorld
                )}
              >
                {"Immersion in the Sailor's world\n"}
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__xEWqu)}
                displayHeight={"396px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"433px"}
                loading={"lazy"}
                src={{
                  src: vector389MQpMs7J2O,
                  fullWidth: 433,
                  fullHeight: 396,
                  aspectRatio: 1.093434
                }}
              />

              <div
                data-plasmic-name={"empoweringMentoringArtist"}
                data-plasmic-override={overrides.empoweringMentoringArtist}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.empoweringMentoringArtist
                )}
              >
                {"Empowering & mentoring artist\n"}
              </div>

              <div
                data-plasmic-name={"fichierDeTravail281"}
                data-plasmic-override={overrides.fichierDeTravail281}
                className={classNames(projectcss.all, sty.fichierDeTravail281)}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__hmMH)}
                displayHeight={"224px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"420px"}
                loading={"lazy"}
                src={{
                  src: frame19NFnEizwfIa,
                  fullWidth: 420,
                  fullHeight: 224,
                  aspectRatio: 1.875
                }}
              />

              <Frame18Icon
                className={classNames(projectcss.all, sty.svg__imyt)}
                role={"img"}
              />

              <Vector37Icon
                className={classNames(projectcss.all, sty.svg__cxpYo)}
                role={"img"}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "freeBox",
    "figmaPaste",
    "immersionInTheSailorsWorld",
    "empoweringMentoringArtist",
    "fichierDeTravail281"
  ],

  header: ["header"],
  freeBox: [
    "freeBox",
    "figmaPaste",
    "immersionInTheSailorsWorld",
    "empoweringMentoringArtist",
    "fichierDeTravail281"
  ],

  figmaPaste: [
    "figmaPaste",
    "immersionInTheSailorsWorld",
    "empoweringMentoringArtist",
    "fichierDeTravail281"
  ],

  immersionInTheSailorsWorld: ["immersionInTheSailorsWorld"],
  empoweringMentoringArtist: ["empoweringMentoringArtist"],
  fichierDeTravail281: ["fichierDeTravail281"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicVision__ArgProps,
      internalVariantPropNames: PlasmicVision__VariantProps
    });

    return PlasmicVision__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVision";
  } else {
    func.displayName = `PlasmicVision.${nodeName}`;
  }
  return func;
}

export const PlasmicVision = Object.assign(
  // Top-level PlasmicVision renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    freeBox: makeNodeComponent("freeBox"),
    figmaPaste: makeNodeComponent("figmaPaste"),
    immersionInTheSailorsWorld: makeNodeComponent("immersionInTheSailorsWorld"),
    empoweringMentoringArtist: makeNodeComponent("empoweringMentoringArtist"),
    fichierDeTravail281: makeNodeComponent("fichierDeTravail281"),
    // Metadata about props expected for PlasmicVision
    internalVariantProps: PlasmicVision__VariantProps,
    internalArgProps: PlasmicVision__ArgProps
  }
);

export default PlasmicVision;
/* prettier-ignore-end */
