// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6tP4H2YXq73abyMEePhpsf
// Component: YFLbf8Sj1U
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import MyHeader from "../../MyHeader"; // plasmic-import: sfUx3YtoOJF/component
import Button from "../../Button"; // plasmic-import: XuXn_eVAMfJ/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_sailor_alpha.module.css"; // plasmic-import: 6tP4H2YXq73abyMEePhpsf/projectcss
import sty from "./PlasmicArtwork.module.css"; // plasmic-import: YFLbf8Sj1U/css

export const PlasmicArtwork__VariantProps = new Array();

export const PlasmicArtwork__ArgProps = new Array();

function PlasmicArtwork__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <MyHeader
            data-plasmic-name={"myHeader"}
            data-plasmic-override={overrides.myHeader}
            className={classNames("__wab_instance", sty.myHeader)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__ky2WG)}>
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#FFFFFF" }}
                >
                  {"Hello artwork"}
                </span>
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </h1>

            <div className={classNames(projectcss.all, sty.freeBox__oDxDp)}>
              <Button
                data-plasmic-name={"mintButton"}
                data-plasmic-override={overrides.mintButton}
                className={classNames("__wab_instance", sty.mintButton)}
              >
                {"Mint"}
              </Button>

              <Button
                data-plasmic-name={"mintButtonBeta"}
                data-plasmic-override={overrides.mintButtonBeta}
                className={classNames("__wab_instance", sty.mintButtonBeta)}
              >
                {"Mint Beta"}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "myHeader", "h1", "mintButton", "mintButtonBeta"],
  myHeader: ["myHeader"],
  h1: ["h1"],
  mintButton: ["mintButton"],
  mintButtonBeta: ["mintButtonBeta"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicArtwork__ArgProps,
      internalVariantPropNames: PlasmicArtwork__VariantProps
    });

    return PlasmicArtwork__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArtwork";
  } else {
    func.displayName = `PlasmicArtwork.${nodeName}`;
  }
  return func;
}

export const PlasmicArtwork = Object.assign(
  // Top-level PlasmicArtwork renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    myHeader: makeNodeComponent("myHeader"),
    h1: makeNodeComponent("h1"),
    mintButton: makeNodeComponent("mintButton"),
    mintButtonBeta: makeNodeComponent("mintButtonBeta"),
    // Metadata about props expected for PlasmicArtwork
    internalVariantProps: PlasmicArtwork__VariantProps,
    internalArgProps: PlasmicArtwork__ArgProps
  }
);

export default PlasmicArtwork;
/* prettier-ignore-end */
