// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6tP4H2YXq73abyMEePhpsf
// Component: CFz-I9uXMp
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 9HJOL_ndHV/component
import Slider from "react-slick"; // plasmic-import: HOQUyOpClJ/codeComponent
import Footer from "../../Footer"; // plasmic-import: w_pxODdXjgL/component
import { useScreenVariants as useScreenVariantsu0VQjvxy5SkDm } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: U0vQjvxy5SKDm/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_sailor_alpha.module.css"; // plasmic-import: 6tP4H2YXq73abyMEePhpsf/projectcss
import sty from "./PlasmicGallery.module.css"; // plasmic-import: CFz-I9uXMp/css
import masque28DistkjdS from "./images/masque2.png"; // plasmic-import: 8distkjdS/picture
import masque4Vat1SKpnd from "./images/masque4.png"; // plasmic-import: VAT1S_Kpnd/picture
import masque6O5ZcT0ZhKa from "./images/masque6.png"; // plasmic-import: O5ZcT0zhKa/picture
import masque7Ba4GpSn2Ji from "./images/masque7.png"; // plasmic-import: ba4gpSn2Ji/picture
import masque8B0GKmTrgkH from "./images/masque8.png"; // plasmic-import: B0gKmTrgkH/picture
import masque9Pkp75Iup8N from "./images/masque9.png"; // plasmic-import: PKP75iup8N/picture
import masque115BueXh3Eos from "./images/masque11.png"; // plasmic-import: 5BUEXh3EOS/picture
import masque12Go3S3DHhz from "./images/masque12.png"; // plasmic-import: -GO3s3DHhz/picture
import masque14RzCmEh4Sa4 from "./images/masque14.png"; // plasmic-import: RzCmEH4SA4/picture
import masque15Qe8OSuvLhF from "./images/masque15.png"; // plasmic-import: Qe8oSUVLhF/picture
import masque18KqxWtBJnPk from "./images/masque18.png"; // plasmic-import: kqxWtBJnPK/picture
import nft2CaImCIbh7OT from "./images/nft2.png"; // plasmic-import: CAImCIbh7oT/picture
import nft3I4UYce1FlU1 from "./images/nft3.png"; // plasmic-import: i4UYce1flU1/picture
import nft13LrJqBEcrbv from "./images/nft1.png"; // plasmic-import: 3LrJqBEcrbv/picture

export const PlasmicGallery__VariantProps = new Array();

export const PlasmicGallery__ArgProps = new Array("_1", "_2");

export const defaultGallery__Args = {};

function PlasmicGallery__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultGallery__Args, props.args);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsu0VQjvxy5SkDm()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
            light={true}
          />

          <div
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div
              data-plasmic-name={"scroll"}
              data-plasmic-override={overrides.scroll}
              className={classNames(projectcss.all, sty.scroll)}
            >
              <div
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                className={classNames(projectcss.all, sty.freeBox)}
              >
                {true ? (
                  <div
                    data-plasmic-name={"_1"}
                    data-plasmic-override={overrides._1}
                    className={classNames(projectcss.all, sty._1)}
                  >
                    {p.renderPlasmicSlot({
                      defaultContents: (
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__femV)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: masque28DistkjdS,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      ),

                      value: args._1
                    })}
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_2"}
                    data-plasmic-override={overrides._2}
                    className={classNames(projectcss.all, sty._2)}
                  >
                    {p.renderPlasmicSlot({
                      defaultContents: (
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__g4R3M)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: masque4Vat1SKpnd,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      ),

                      value: args._2
                    })}
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_3"}
                    data-plasmic-override={overrides._3}
                    className={classNames(projectcss.all, sty._3)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xrL44)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque6O5ZcT0ZhKa,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_4"}
                    data-plasmic-override={overrides._4}
                    className={classNames(projectcss.all, sty._4)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__yQgj)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque7Ba4GpSn2Ji,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_5"}
                    data-plasmic-override={overrides._5}
                    className={classNames(projectcss.all, sty._5)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__kDkwn)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque8B0GKmTrgkH,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_6"}
                    data-plasmic-override={overrides._6}
                    className={classNames(projectcss.all, sty._6)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tQuem)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque9Pkp75Iup8N,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_7"}
                    data-plasmic-override={overrides._7}
                    className={classNames(projectcss.all, sty._7)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__nhMl)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque115BueXh3Eos,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_8"}
                    data-plasmic-override={overrides._8}
                    className={classNames(projectcss.all, sty._8)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__iJhm1)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque12Go3S3DHhz,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_9"}
                    data-plasmic-override={overrides._9}
                    className={classNames(projectcss.all, sty._9)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__yeN)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque14RzCmEh4Sa4,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_10"}
                    data-plasmic-override={overrides._10}
                    className={classNames(projectcss.all, sty._10)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__edNl)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque15Qe8OSuvLhF,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_11"}
                    data-plasmic-override={overrides._11}
                    className={classNames(projectcss.all, sty._11)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__iobXq)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: masque18KqxWtBJnPk,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
                {true ? (
                  <div
                    data-plasmic-name={"_12"}
                    data-plasmic-override={overrides._12}
                    className={classNames(projectcss.all, sty._12)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__usjLc)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"200px"}
                      loading={"lazy"}
                      src={{
                        src: nft2CaImCIbh7OT,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}
              </div>
            </div>

            {true ? (
              <div
                data-plasmic-name={"column1"}
                data-plasmic-override={overrides.column1}
                className={classNames(projectcss.all, sty.column1)}
              />
            ) : null}
            {true ? (
              <div
                data-plasmic-name={"column2"}
                data-plasmic-override={overrides.column2}
                className={classNames(projectcss.all, sty.column2)}
              >
                {true ? (
                  <div
                    data-plasmic-name={"focus"}
                    data-plasmic-override={overrides.focus}
                    className={classNames(projectcss.all, sty.focus)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__cgBtW)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: nft3I4UYce1FlU1,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                ) : null}

                <Slider
                  data-plasmic-name={"slider"}
                  data-plasmic-override={overrides.slider}
                  arrows={false}
                  autoplay={true}
                  autoplaySpeed={2000}
                  className={classNames("__wab_instance", sty.slider)}
                  easing={""}
                  fade={true}
                  speed={50}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jK9KK)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: nft13LrJqBEcrbv,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qq55Q)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque28DistkjdS,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___4DKgB)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque4Vat1SKpnd,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cmoJx)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque6O5ZcT0ZhKa,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__quRiu)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque7Ba4GpSn2Ji,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__eZxgm)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque8B0GKmTrgkH,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__m6Xyp)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque9Pkp75Iup8N,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__hnIb)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque115BueXh3Eos,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ba6Ik)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque12Go3S3DHhz,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wrwXp)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque14RzCmEh4Sa4,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__x627K)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: masque15Qe8OSuvLhF,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__uli67)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: nft2CaImCIbh7OT,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />
                </Slider>
              </div>
            ) : null}
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "section",
    "scroll",
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "column1",
    "column2",
    "focus",
    "slider",
    "footer"
  ],

  header: ["header"],
  section: [
    "section",
    "scroll",
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "column1",
    "column2",
    "focus",
    "slider"
  ],

  scroll: [
    "scroll",
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12"
  ],

  freeBox: [
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12"
  ],

  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  _4: ["_4"],
  _5: ["_5"],
  _6: ["_6"],
  _7: ["_7"],
  _8: ["_8"],
  _9: ["_9"],
  _10: ["_10"],
  _11: ["_11"],
  _12: ["_12"],
  column1: ["column1"],
  column2: ["column2", "focus", "slider"],
  focus: ["focus"],
  slider: ["slider"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicGallery__ArgProps,
      internalVariantPropNames: PlasmicGallery__VariantProps
    });

    return PlasmicGallery__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGallery";
  } else {
    func.displayName = `PlasmicGallery.${nodeName}`;
  }
  return func;
}

export const PlasmicGallery = Object.assign(
  // Top-level PlasmicGallery renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    section: makeNodeComponent("section"),
    scroll: makeNodeComponent("scroll"),
    freeBox: makeNodeComponent("freeBox"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    _5: makeNodeComponent("_5"),
    _6: makeNodeComponent("_6"),
    _7: makeNodeComponent("_7"),
    _8: makeNodeComponent("_8"),
    _9: makeNodeComponent("_9"),
    _10: makeNodeComponent("_10"),
    _11: makeNodeComponent("_11"),
    _12: makeNodeComponent("_12"),
    column1: makeNodeComponent("column1"),
    column2: makeNodeComponent("column2"),
    focus: makeNodeComponent("focus"),
    slider: makeNodeComponent("slider"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicGallery
    internalVariantProps: PlasmicGallery__VariantProps,
    internalArgProps: PlasmicGallery__ArgProps
  }
);

export default PlasmicGallery;
/* prettier-ignore-end */
