// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6tP4H2YXq73abyMEePhpsf
// Component: PXpi17MlSes
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 9HJOL_ndHV/component
import FocusImage from "../../FocusImage"; // plasmic-import: OYpuIb6c8w/component
import Footer from "../../Footer"; // plasmic-import: w_pxODdXjgL/component
import { useScreenVariants as useScreenVariantsu0VQjvxy5SkDm } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: U0vQjvxy5SKDm/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_sailor_alpha.module.css"; // plasmic-import: 6tP4H2YXq73abyMEePhpsf/projectcss
import sty from "./PlasmicGallery2.module.css"; // plasmic-import: PXpi17MlSes/css
import masque28DistkjdS from "./images/masque2.png"; // plasmic-import: 8distkjdS/picture
import masque4Vat1SKpnd from "./images/masque4.png"; // plasmic-import: VAT1S_Kpnd/picture
import masque6O5ZcT0ZhKa from "./images/masque6.png"; // plasmic-import: O5ZcT0zhKa/picture
import masque7Ba4GpSn2Ji from "./images/masque7.png"; // plasmic-import: ba4gpSn2Ji/picture
import masque8B0GKmTrgkH from "./images/masque8.png"; // plasmic-import: B0gKmTrgkH/picture
import masque9Pkp75Iup8N from "./images/masque9.png"; // plasmic-import: PKP75iup8N/picture
import masque115BueXh3Eos from "./images/masque11.png"; // plasmic-import: 5BUEXh3EOS/picture
import masque12Go3S3DHhz from "./images/masque12.png"; // plasmic-import: -GO3s3DHhz/picture
import masque14RzCmEh4Sa4 from "./images/masque14.png"; // plasmic-import: RzCmEH4SA4/picture
import masque15Qe8OSuvLhF from "./images/masque15.png"; // plasmic-import: Qe8oSUVLhF/picture
import masque18KqxWtBJnPk from "./images/masque18.png"; // plasmic-import: kqxWtBJnPK/picture
import nft2CaImCIbh7OT from "./images/nft2.png"; // plasmic-import: CAImCIbh7oT/picture

export const PlasmicGallery2__VariantProps = new Array();

export const PlasmicGallery2__ArgProps = new Array("selected");

export const defaultGallery2__Args = {};

function PlasmicGallery2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultGallery2__Args, props.args);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsu0VQjvxy5SkDm()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
            light={true}
          />

          <div
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            {true ? (
              <div
                data-plasmic-name={"scroll"}
                data-plasmic-override={overrides.scroll}
                className={classNames(projectcss.all, sty.scroll)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__tpqJr)}>
                  {true ? (
                    <div
                      data-plasmic-name={"_1"}
                      data-plasmic-override={overrides._1}
                      className={classNames(projectcss.all, sty._1)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__vMrwr)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque28DistkjdS,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_2"}
                      data-plasmic-override={overrides._2}
                      className={classNames(projectcss.all, sty._2)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__eSwrd)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque4Vat1SKpnd,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_3"}
                      data-plasmic-override={overrides._3}
                      className={classNames(projectcss.all, sty._3)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___6MPu)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque6O5ZcT0ZhKa,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_4"}
                      data-plasmic-override={overrides._4}
                      className={classNames(projectcss.all, sty._4)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__noPjS)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque7Ba4GpSn2Ji,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_5"}
                      data-plasmic-override={overrides._5}
                      className={classNames(projectcss.all, sty._5)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__saprZ)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque8B0GKmTrgkH,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_6"}
                      data-plasmic-override={overrides._6}
                      className={classNames(projectcss.all, sty._6)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___9G20H)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque9Pkp75Iup8N,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_7"}
                      data-plasmic-override={overrides._7}
                      className={classNames(projectcss.all, sty._7)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__t5RYy)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque115BueXh3Eos,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_8"}
                      data-plasmic-override={overrides._8}
                      className={classNames(projectcss.all, sty._8)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___7G5Ph)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque12Go3S3DHhz,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_9"}
                      data-plasmic-override={overrides._9}
                      className={classNames(projectcss.all, sty._9)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___3AfM1)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque14RzCmEh4Sa4,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_10"}
                      data-plasmic-override={overrides._10}
                      className={classNames(projectcss.all, sty._10)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hgaod)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque15Qe8OSuvLhF,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_11"}
                      data-plasmic-override={overrides._11}
                      className={classNames(projectcss.all, sty._11)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__dCnGj)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: masque18KqxWtBJnPk,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      data-plasmic-name={"_12"}
                      data-plasmic-override={overrides._12}
                      className={classNames(projectcss.all, sty._12)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__xHs2L)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"200px"}
                        loading={"lazy"}
                        src={{
                          src: nft2CaImCIbh7OT,
                          fullWidth: 1181,
                          fullHeight: 1181,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  ) : null}
                </div>
              </div>
            ) : null}
            {true ? (
              <div
                data-plasmic-name={"bigImage"}
                data-plasmic-override={overrides.bigImage}
                className={classNames(projectcss.all, sty.bigImage)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__feTtq)}>
                  {p.renderPlasmicSlot({
                    defaultContents: (
                      <FocusImage
                        className={classNames(
                          "__wab_instance",
                          sty.focusImage__s6EQt
                        )}
                        name={"FocusImage"}
                      />
                    ),

                    value: args.selected
                  })}
                </div>
              </div>
            ) : null}
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "section",
    "scroll",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "bigImage",
    "footer"
  ],

  header: ["header"],
  section: [
    "section",
    "scroll",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "bigImage"
  ],

  scroll: [
    "scroll",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12"
  ],

  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  _4: ["_4"],
  _5: ["_5"],
  _6: ["_6"],
  _7: ["_7"],
  _8: ["_8"],
  _9: ["_9"],
  _10: ["_10"],
  _11: ["_11"],
  _12: ["_12"],
  bigImage: ["bigImage"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicGallery2__ArgProps,
      internalVariantPropNames: PlasmicGallery2__VariantProps
    });

    return PlasmicGallery2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGallery2";
  } else {
    func.displayName = `PlasmicGallery2.${nodeName}`;
  }
  return func;
}

export const PlasmicGallery2 = Object.assign(
  // Top-level PlasmicGallery2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    section: makeNodeComponent("section"),
    scroll: makeNodeComponent("scroll"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    _5: makeNodeComponent("_5"),
    _6: makeNodeComponent("_6"),
    _7: makeNodeComponent("_7"),
    _8: makeNodeComponent("_8"),
    _9: makeNodeComponent("_9"),
    _10: makeNodeComponent("_10"),
    _11: makeNodeComponent("_11"),
    _12: makeNodeComponent("_12"),
    bigImage: makeNodeComponent("bigImage"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicGallery2
    internalVariantProps: PlasmicGallery2__VariantProps,
    internalArgProps: PlasmicGallery2__ArgProps
  }
);

export default PlasmicGallery2;
/* prettier-ignore-end */
