// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6tP4H2YXq73abyMEePhpsf
// Component: YFLbf8Sj1U
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 9HJOL_ndHV/component
import Slider from "react-slick"; // plasmic-import: HOQUyOpClJ/codeComponent
import Footer from "../../Footer"; // plasmic-import: w_pxODdXjgL/component
import { useScreenVariants as useScreenVariantsu0VQjvxy5SkDm } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: U0vQjvxy5SKDm/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_sailor_alpha.module.css"; // plasmic-import: 6tP4H2YXq73abyMEePhpsf/projectcss
import sty from "./PlasmicArtwork.module.css"; // plasmic-import: YFLbf8Sj1U/css
import titre1FFjsUvpvre from "./images/titre1.png"; // plasmic-import: fFJSUvpvre/picture
import titre1PngHD0J16Vls from "./images/titre1Png.png"; // plasmic-import: hD0j16vls/picture
import masque28DistkjdS from "./images/masque2.png"; // plasmic-import: 8distkjdS/picture
import masque4Vat1SKpnd from "./images/masque4.png"; // plasmic-import: VAT1S_Kpnd/picture
import masque6O5ZcT0ZhKa from "./images/masque6.png"; // plasmic-import: O5ZcT0zhKa/picture
import masque7Ba4GpSn2Ji from "./images/masque7.png"; // plasmic-import: ba4gpSn2Ji/picture
import masque8B0GKmTrgkH from "./images/masque8.png"; // plasmic-import: B0gKmTrgkH/picture
import masque9Pkp75Iup8N from "./images/masque9.png"; // plasmic-import: PKP75iup8N/picture
import masque115BueXh3Eos from "./images/masque11.png"; // plasmic-import: 5BUEXh3EOS/picture
import masque12Go3S3DHhz from "./images/masque12.png"; // plasmic-import: -GO3s3DHhz/picture
import masque14RzCmEh4Sa4 from "./images/masque14.png"; // plasmic-import: RzCmEH4SA4/picture
import masque15Qe8OSuvLhF from "./images/masque15.png"; // plasmic-import: Qe8oSUVLhF/picture
import masque18KqxWtBJnPk from "./images/masque18.png"; // plasmic-import: kqxWtBJnPK/picture
import nft3I4UYce1FlU1 from "./images/nft3.png"; // plasmic-import: i4UYce1flU1/picture

export const PlasmicArtwork__VariantProps = new Array();

export const PlasmicArtwork__ArgProps = new Array();

export const defaultArtwork__Args = {};

function PlasmicArtwork__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultArtwork__Args, props.args);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsu0VQjvxy5SkDm()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div className={classNames(projectcss.all, sty.freeBox___3SVom)}>
            <div className={classNames(projectcss.all, sty.freeBox___1TSrX)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__eIpfC)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "80%"
                    : "33%"
                }
                loading={"lazy"}
                src={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? {
                        src: titre1PngHD0J16Vls,
                        fullWidth: 431,
                        fullHeight: 294,
                        aspectRatio: undefined
                      }
                    : {
                        src: titre1FFjsUvpvre,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }
                }
              />

              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {
                  "“2020. Le monde s’est arrêté en sombrant dans une dictature sanitaire mondiale. Sailor est un marin solitaire parcourant le monde entier. Il est à la recherche de coins sauvages et tranquilles où il pourra s’évader dans les méandres de son imagination et s’abandonner à la poésie. Alors qu’il fuit “Babylone”, le coeur de l’humanité 2.0, il collectionne les petits boulots afin d’économiser et de se procurer un rafiot digne de concourir à sa grande échappée. Mais Dieu seul sait ce que son voyage lui réserve...”"
                }
              </div>
            </div>

            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__pOlS1)}>
                <div className={classNames(projectcss.all, sty.freeBox__y805G)}>
                  <Slider
                    data-plasmic-name={"slider"}
                    data-plasmic-override={overrides.slider}
                    adaptiveHeight={false}
                    className={classNames("__wab_instance", sty.slider)}
                    slidesPerRow={2}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__yANqc)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque28DistkjdS,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hpsri)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque4Vat1SKpnd,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__aBVq)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque6O5ZcT0ZhKa,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__zjXnS)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque7Ba4GpSn2Ji,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___0Stz)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque8B0GKmTrgkH,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__weMu4)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque9Pkp75Iup8N,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__qr82F)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque115BueXh3Eos,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ffX1M)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque12Go3S3DHhz,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ybOjv)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque14RzCmEh4Sa4,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__zzM8W)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque15Qe8OSuvLhF,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__u7Gb)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: masque18KqxWtBJnPk,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pS5L)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"50%"}
                      loading={"lazy"}
                      src={{
                        src: nft3I4UYce1FlU1,
                        fullWidth: 1181,
                        fullHeight: 1181,
                        aspectRatio: undefined
                      }}
                    />
                  </Slider>
                </div>
              </div>
            ) : null}
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "text", "slider", "footer"],
  header: ["header"],
  text: ["text"],
  slider: ["slider"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicArtwork__ArgProps,
      internalVariantPropNames: PlasmicArtwork__VariantProps
    });

    return PlasmicArtwork__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArtwork";
  } else {
    func.displayName = `PlasmicArtwork.${nodeName}`;
  }
  return func;
}

export const PlasmicArtwork = Object.assign(
  // Top-level PlasmicArtwork renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    slider: makeNodeComponent("slider"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicArtwork
    internalVariantProps: PlasmicArtwork__VariantProps,
    internalArgProps: PlasmicArtwork__ArgProps
  }
);

export default PlasmicArtwork;
/* prettier-ignore-end */
