// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6tP4H2YXq73abyMEePhpsf
// Component: CFz-I9uXMp
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 9HJOL_ndHV/component
import { useScreenVariants as useScreenVariantsu0VQjvxy5SkDm } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: U0vQjvxy5SKDm/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_sailor_alpha.module.css"; // plasmic-import: 6tP4H2YXq73abyMEePhpsf/projectcss
import sty from "./PlasmicGallery.module.css"; // plasmic-import: CFz-I9uXMp/css
import nft13LrJqBEcrbv from "./images/nft1.png"; // plasmic-import: 3LrJqBEcrbv/picture
import nft2CaImCIbh7OT from "./images/nft2.png"; // plasmic-import: CAImCIbh7oT/picture
import nft3I4UYce1FlU1 from "./images/nft3.png"; // plasmic-import: i4UYce1flU1/picture
import nft4XHwUai6Q7C from "./images/nft4.png"; // plasmic-import: -xHwUAI6q7c/picture
import nft5ZJyUFs8I0X from "./images/nft5.png"; // plasmic-import: z-jyUFs8i0x/picture
import nft66SvKTzPzKlc from "./images/nft6.png"; // plasmic-import: 6SvKTzPzKLC/picture

export const PlasmicGallery__VariantProps = new Array();

export const PlasmicGallery__ArgProps = new Array("_1");

export const defaultGallery__Args = {};

function PlasmicGallery__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultGallery__Args, props.args);
  const $props = args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsu0VQjvxy5SkDm()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
            light={true}
          />

          <div
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            {true ? (
              <div
                data-plasmic-name={"column1"}
                data-plasmic-override={overrides.column1}
                className={classNames(projectcss.all, sty.column1)}
              >
                <div
                  data-plasmic-name={"scroll"}
                  data-plasmic-override={overrides.scroll}
                  className={classNames(projectcss.all, sty.scroll)}
                >
                  <div
                    data-plasmic-name={"freeBox"}
                    data-plasmic-override={overrides.freeBox}
                    className={classNames(projectcss.all, sty.freeBox)}
                  >
                    {true ? (
                      <div
                        data-plasmic-name={"_1"}
                        data-plasmic-override={overrides._1}
                        className={classNames(projectcss.all, sty._1)}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: (
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__femV)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"200px"}
                              loading={"lazy"}
                              src={{
                                src: nft13LrJqBEcrbv,
                                fullWidth: 1181,
                                fullHeight: 1181,
                                aspectRatio: undefined
                              }}
                            />
                          ),

                          value: args._1
                        })}
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_2"}
                        data-plasmic-override={overrides._2}
                        className={classNames(projectcss.all, sty._2)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__gApNi)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft2CaImCIbh7OT,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_3"}
                        data-plasmic-override={overrides._3}
                        className={classNames(projectcss.all, sty._3)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__xrL44)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft3I4UYce1FlU1,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_4"}
                        data-plasmic-override={overrides._4}
                        className={classNames(projectcss.all, sty._4)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yQgj)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft4XHwUai6Q7C,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_5"}
                        data-plasmic-override={overrides._5}
                        className={classNames(projectcss.all, sty._5)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__kDkwn)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft5ZJyUFs8I0X,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_6"}
                        data-plasmic-override={overrides._6}
                        className={classNames(projectcss.all, sty._6)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__tQuem)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft66SvKTzPzKlc,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_7"}
                        data-plasmic-override={overrides._7}
                        className={classNames(projectcss.all, sty._7)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__nhMl)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_8"}
                        data-plasmic-override={overrides._8}
                        className={classNames(projectcss.all, sty._8)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__iJhm1)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_9"}
                        data-plasmic-override={overrides._9}
                        className={classNames(projectcss.all, sty._9)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yeN)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_10"}
                        data-plasmic-override={overrides._10}
                        className={classNames(projectcss.all, sty._10)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__edNl)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_11"}
                        data-plasmic-override={overrides._11}
                        className={classNames(projectcss.all, sty._11)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__iobXq)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_12"}
                        data-plasmic-override={overrides._12}
                        className={classNames(projectcss.all, sty._12)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__usjLc)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_13"}
                        data-plasmic-override={overrides._13}
                        className={classNames(projectcss.all, sty._13)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__qJkDy)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_14"}
                        data-plasmic-override={overrides._14}
                        className={classNames(projectcss.all, sty._14)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__hj4Nr)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_15"}
                        data-plasmic-override={overrides._15}
                        className={classNames(projectcss.all, sty._15)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__o7F)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_16"}
                        data-plasmic-override={overrides._16}
                        className={classNames(projectcss.all, sty._16)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__m6KOg)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_17"}
                        data-plasmic-override={overrides._17}
                        className={classNames(projectcss.all, sty._17)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__gKzsu)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                    {true ? (
                      <div
                        data-plasmic-name={"_18"}
                        data-plasmic-override={overrides._18}
                        className={classNames(projectcss.all, sty._18)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___8QKio)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"200px"}
                          loading={"lazy"}
                          src={{
                            src: nft13LrJqBEcrbv,
                            fullWidth: 1181,
                            fullHeight: 1181,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    ) : null}
                  </div>
                </div>
              </div>
            ) : null}
            {true ? (
              <div
                data-plasmic-name={"column2"}
                data-plasmic-override={overrides.column2}
                className={classNames(projectcss.all, sty.column2)}
              >
                <div
                  data-plasmic-name={"focus"}
                  data-plasmic-override={overrides.focus}
                  className={classNames(projectcss.all, sty.focus)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cgBtW)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: nft3I4UYce1FlU1,
                      fullWidth: 1181,
                      fullHeight: 1181,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            ) : null}
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "section",
    "column1",
    "scroll",
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "_13",
    "_14",
    "_15",
    "_16",
    "_17",
    "_18",
    "column2",
    "focus"
  ],

  header: ["header"],
  section: [
    "section",
    "column1",
    "scroll",
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "_13",
    "_14",
    "_15",
    "_16",
    "_17",
    "_18",
    "column2",
    "focus"
  ],

  column1: [
    "column1",
    "scroll",
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "_13",
    "_14",
    "_15",
    "_16",
    "_17",
    "_18"
  ],

  scroll: [
    "scroll",
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "_13",
    "_14",
    "_15",
    "_16",
    "_17",
    "_18"
  ],

  freeBox: [
    "freeBox",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
    "_10",
    "_11",
    "_12",
    "_13",
    "_14",
    "_15",
    "_16",
    "_17",
    "_18"
  ],

  _1: ["_1"],
  _2: ["_2"],
  _3: ["_3"],
  _4: ["_4"],
  _5: ["_5"],
  _6: ["_6"],
  _7: ["_7"],
  _8: ["_8"],
  _9: ["_9"],
  _10: ["_10"],
  _11: ["_11"],
  _12: ["_12"],
  _13: ["_13"],
  _14: ["_14"],
  _15: ["_15"],
  _16: ["_16"],
  _17: ["_17"],
  _18: ["_18"],
  column2: ["column2", "focus"],
  focus: ["focus"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicGallery__ArgProps,
      internalVariantPropNames: PlasmicGallery__VariantProps
    });

    return PlasmicGallery__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGallery";
  } else {
    func.displayName = `PlasmicGallery.${nodeName}`;
  }
  return func;
}

export const PlasmicGallery = Object.assign(
  // Top-level PlasmicGallery renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    section: makeNodeComponent("section"),
    column1: makeNodeComponent("column1"),
    scroll: makeNodeComponent("scroll"),
    freeBox: makeNodeComponent("freeBox"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _3: makeNodeComponent("_3"),
    _4: makeNodeComponent("_4"),
    _5: makeNodeComponent("_5"),
    _6: makeNodeComponent("_6"),
    _7: makeNodeComponent("_7"),
    _8: makeNodeComponent("_8"),
    _9: makeNodeComponent("_9"),
    _10: makeNodeComponent("_10"),
    _11: makeNodeComponent("_11"),
    _12: makeNodeComponent("_12"),
    _13: makeNodeComponent("_13"),
    _14: makeNodeComponent("_14"),
    _15: makeNodeComponent("_15"),
    _16: makeNodeComponent("_16"),
    _17: makeNodeComponent("_17"),
    _18: makeNodeComponent("_18"),
    column2: makeNodeComponent("column2"),
    focus: makeNodeComponent("focus"),
    // Metadata about props expected for PlasmicGallery
    internalVariantProps: PlasmicGallery__VariantProps,
    internalArgProps: PlasmicGallery__ArgProps
  }
);

export default PlasmicGallery;
/* prettier-ignore-end */
